##
# Services needed to run Magento2 application on Docker
#
# Docker Compose defines required services and attach them together through aliases
##
version: '2'
services:
  db:
    container_name: magento2devbox_db_1
    restart: always
    image: mysql:5.6
    ports:
      - "1345:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento2
    volumes:
      - ../../shared/db:/var/lib/mysql
  rabbit:
    container_name: magento2devbox_rabbit_1
    image: rabbitmq:3-management
    ports:
      - "8282:15672"
      - "5672:5672"
  redis:
    container_name: magento2devbox_redis_1
    image: redis:3.0.7
  varnish:
    container_name: magento2devbox_varnish_1
    image: magento/magento2devbox_varnish:latest
    volumes:
      - ../shared/configs/varnish:/etc/varnish/default
    links:
      - web:web
    ports:
      - "1748:6081"
  web:
    container_name: magento2devbox_web_1
    build: ../web
    volumes:
      - ../shared/magento:/home/magento2/magento2
      - ../shared/.composer:/home/magento2/.composer
      - ../shared/.ssh:/home/magento2/.ssh
      - ../shared/.magento-cloud:/home/magento2/.magento-cloud
      - ../shared/configs/varnish:/home/magento2/configs/varnish
    ports:
      - "1749:80"
